### ISSUE TITLE
`hostname` error

### ISSUE THREAD

**Issue by max-cx** [Vale-at-Red-Hat/vale-at-red-hat#119]
**Describe the bug**

![image](https://user-images.githubusercontent.com/78564304/145041231-9da389aa-8338-4ee5-a94f-7a42566b1694.png)

IBM Style (p. 292):
![image](https://user-images.githubusercontent.com/78564304/145041330-d79e6180-c5cd-4adf-84d8-c00f02980dfd.png)

Meanwhile:
![image](https://user-images.githubusercontent.com/78564304/145043425-efbcbb54-ea57-4ad2-bbd0-8ec9a94fb711.png)

**To Reproduce**

1. Add this word or expression:
2. Vale reports an illegitimate alert: error, warning, suggestion.

**Expected behavior**

**Additional context**
Add any other context here.

**Comment by themr0c** [comment]
https://github.com/Vale-at-Red-Hat/vale-at-red-hat/blob/main/.vale/styles/RedHat/Spelling.yml is already good.
