### ISSUE TITLE
Do we need a style for stylepedia?

### ISSUE THREAD

**Issue by rolfedh** [Vale-at-Red-Hat/vale-at-red-hat#24]
**Is your feature request related to a problem? Please describe.**

According to [FAQs: CCS style guides and term conventions](https://source.redhat.com/groups/public/ccs/ccs_wiki/ccs_style_guides_and_term_conventions), "[The Red Hat Technical Publications Writing Style Guide (stylepedia.net)](http://stylepedia.net/) is no longer being used in CCS. It is still in use outside CCS, but it is no longer official for our group."

HOWEVER, Ingrid Towey states that stylepedia is still used by some people upstream (we're not sure who) and a technical docs group under Sales.

- Who are these users?
- Do their tools and file formats support Vale style linter?
- Do they want or need a Vale style?
- Do we want this Vale style for Red Hat project to include non-CCS use cases?
- What is the priority of such a project? 

**Describe the solution you'd like**

Depending on our conversations and the answers to the preceding questions, it might make sense to include stylepedia within the scope of this project. If so, we would create a stylepedia subdirectory in the Red Hat style and begin creating rules from it. 

**Describe alternatives you've considered**

If the tools and file format of stylepedia users do not support Vale, they might consider using other style-checker tools such as Acrolink, Grammarly, and so on.

**Additional context**

**Comment by themr0c** [comment]
I believe it is safe to leave Stylepedia out from the RedHat  style guide that we implement here. I don't see the point in implementing rules that we have deprecated.

**Comment by bburt-rh** [comment]
I agree with @themr0c. These styles are deprecated. It seems like a waste of time to implement them if they are being phased out.

**Comment by max-cx** [comment]
Stylepedia may useful as a reference on some points, but that doesn't mean that its content should be implemented in Vale.

**Comment by rolfedh** [comment]
We have voted to close this issue because stylepedia is obsolete and not relevant to the target user group.
