### ISSUE TITLE
Cite https://source.redhat.com/groups/public/ccs/ccs_wiki/ccs_style_guides_and_term_conventions

### ISSUE THREAD

**Issue by rolfedh** [Vale-at-Red-Hat/vale-at-red-hat#25]
**Is your feature request related to a problem? Please describe.**

Cite https://source.redhat.com/groups/public/ccs/ccs_wiki/ccs_style_guides_and_term_conventions in the list of definitive sources.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by themr0c** [comment]
This document is not public, can we work on having a public version?
