### ISSUE TITLE
Configure this repo for multiple contributors and add a contributors section to the README.

### ISSUE THREAD

**Issue by rolfedh** [Vale-at-Red-Hat/vale-at-red-hat#9]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by michaelryanpeter** [comment]
Please add me as a contributor. My GH handle is michaelryanpeter

**Comment by themr0c** [comment]
I invited everyone who requested it. Closing the issue.
